const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))
const money=(value:number)=>`${Number(value).toLocaleString('fr-FR')} F CFA`

export interface SaleReceipt{settings:{nom:string;telephone?:string;adresse?:string;pied_ticket:string;largeur_ticket:number};vente:{numero:string;created_at:string;sous_total:number;remise:number;total_final:number;montant_paye:number;reste_a_payer:number};caissier:string;client?:string;lignes:Array<{quantite:number;nom_produit:string;prix_unitaire:number;total_ligne:number}>;paiements:Array<{mode:string;montant:number}>}
export function saleReceiptHtml(receipt:SaleReceipt){return`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(receipt.vente.numero)}</title><style>@page{size:${receipt.settings.largeur_ticket||80}mm auto;margin:4mm}body{font:12px ui-monospace,monospace;margin:0;color:#111}h1{text-align:center;font-size:18px}.center{text-align:center}.row{display:flex;justify-content:space-between;gap:8px}.line{border-top:1px dashed #333;margin:8px 0}.due{font-size:15px;font-weight:800}table{width:100%;border-collapse:collapse}td{padding:2px 0;vertical-align:top}td:last-child{text-align:right}</style></head><body><h1>${escapeHtml(receipt.settings.nom)}</h1><p class="center">${escapeHtml(receipt.settings.adresse||'')}<br>${escapeHtml(receipt.settings.telephone||'')}</p><div class="line"></div><p>Vente ${escapeHtml(receipt.vente.numero)}<br>${new Date(receipt.vente.created_at).toLocaleString('fr-FR')}<br>Caissier : ${escapeHtml(receipt.caissier)}${receipt.client?`<br>Client : ${escapeHtml(receipt.client)}`:''}</p><table>${receipt.lignes.map(line=>`<tr><td>${line.quantite} × ${escapeHtml(line.nom_produit)}<br><small>${money(line.prix_unitaire)}</small></td><td>${money(line.total_ligne)}</td></tr>`).join('')}</table><div class="line"></div><div class="row"><span>Sous-total</span><b>${money(receipt.vente.sous_total)}</b></div><div class="row"><span>Remise</span><b>${money(receipt.vente.remise)}</b></div><div class="row"><span>Total</span><b>${money(receipt.vente.total_final)}</b></div><div class="row"><span>Payé</span><b>${money(receipt.vente.montant_paye)}</b></div><div class="row due"><span>Reste</span><b>${money(receipt.vente.reste_a_payer)}</b></div><p>${receipt.paiements.map(p=>`${escapeHtml(p.mode)} : ${money(p.montant)}`).join('<br>')}</p><div class="line"></div><p class="center">${escapeHtml(receipt.settings.pied_ticket)}</p></body></html>`}

export interface RestaurantTicket{numero:string;table?:string;serveur:string;date:string;lignes:Array<{quantite:number;designation:string;prix:number}>;total:number;paye:number;reste:number;mode?:string}
export function restaurantTicketHtml(ticket:RestaurantTicket){return`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(ticket.numero)}</title><style>@page{size:80mm auto;margin:4mm}body{font:12px ui-monospace,monospace}h1{text-align:center}table{width:100%}td:last-child{text-align:right}.total{font-weight:800;font-size:14px}</style></head><body><h1>MG DELICES</h1><p>Commande ${escapeHtml(ticket.numero)}<br>${escapeHtml(ticket.table||'À emporter')} · ${new Date(ticket.date).toLocaleString('fr-FR')}<br>Serveur : ${escapeHtml(ticket.serveur)}</p><table>${ticket.lignes.map(line=>`<tr><td>${line.quantite} × ${escapeHtml(line.designation)}</td><td>${money(line.quantite*line.prix)}</td></tr>`).join('')}</table><hr><p class="total">Total : ${money(ticket.total)}</p><p>Payé : ${money(ticket.paye)}<br>Reste : ${money(ticket.reste)}${ticket.mode?`<br>Paiement : ${escapeHtml(ticket.mode)}`:''}</p><p style="text-align:center">Merci pour votre confiance.</p></body></html>`}

export interface KitchenTicket{numero:string;table?:string;date:string;lignes:Array<{quantite:number;designation:string;notes?:string}>}
export function kitchenTicketHtml(ticket:KitchenTicket){return`<!doctype html><html><head><meta charset="utf-8"><title>Cuisine ${escapeHtml(ticket.numero)}</title><style>@page{size:80mm auto;margin:4mm}body{font:14px ui-monospace,monospace}h1{text-align:center}.item{border-top:1px dashed #333;padding:7px 0;font-weight:800}.notes{font-weight:400}</style></head><body><h1>BON CUISINE</h1><p>${escapeHtml(ticket.table||'À emporter')}<br>Commande ${escapeHtml(ticket.numero)}<br>${new Date(ticket.date).toLocaleString('fr-FR')}</p>${ticket.lignes.map(line=>`<div class="item">${line.quantite} × ${escapeHtml(line.designation)}${line.notes?`<div class="notes">Note : ${escapeHtml(line.notes)}</div>`:''}</div>`).join('')}</body></html>`}

export interface FinancialReceipt{type:string;identifiant:string;reference:string;date:string;tiers?:string;montant:number;mode?:string;utilisateur:string}
export function financialReceiptHtml(receipt:FinancialReceipt){return`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(receipt.identifiant)}</title><style>@page{size:A4;margin:18mm}body{font:14px system-ui;color:#111}h1{color:#064e3b}.amount{font-size:22px;font-weight:800}</style></head><body><h1>MG DELICES</h1><h2>${escapeHtml(receipt.type)}</h2><p>Identifiant : ${escapeHtml(receipt.identifiant)}<br>Référence : ${escapeHtml(receipt.reference)}<br>Date : ${new Date(receipt.date).toLocaleString('fr-FR')}${receipt.tiers?`<br>Tiers : ${escapeHtml(receipt.tiers)}`:''}<br>Utilisateur : ${escapeHtml(receipt.utilisateur)}</p><p class="amount">${money(receipt.montant)}</p>${receipt.mode?`<p>Mode : ${escapeHtml(receipt.mode)}</p>`:''}</body></html>`}

export function printHtml(html:string){const popup=window.open('','_blank','width=480,height=720');if(!popup)throw new Error('Fenêtre d’impression bloquée');popup.document.write(html);popup.document.close();popup.focus();popup.addEventListener('load',()=>popup.print(),{once:true})}
