import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { LoaderCircle, Plus, RotateCcw, Search, X } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { useAuth } from '../contexts/AuthContext'
import { userMessageFromError } from '../lib/errors'
import { formatDateTime, formatMoney } from '../lib/format'
import { returnableQuantity } from '../lib/returns'
import { supabase } from '../lib/supabase'
import type { CustomerReturnSummary, ReturnableSaleDetail } from '../types/returns'

type RefundMethod='especes'|'orange_money'|'moov_money'|'virement'|'avoir'

export function CustomerReturnsPage(){
  const{profile}=useAuth(),[params]=useSearchParams(),canManage=profile?.role==='admin'||profile?.role==='gestionnaire'
  const[items,setItems]=useState<CustomerReturnSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[stockFilter,setStockFilter]=useState('tous')
  const[open,setOpen]=useState(false),[saleId,setSaleId]=useState(params.get('vente')||''),[detail,setDetail]=useState<ReturnableSaleDetail|null>(null),[quantities,setQuantities]=useState<Record<string,number>>({}),[reason,setReason]=useState(''),[restoreStock,setRestoreStock]=useState(false),[cancelEntire,setCancelEntire]=useState(false),[refundMethod,setRefundMethod]=useState<RefundMethod>('avoir'),[busy,setBusy]=useState(false)
  const[refunding,setRefunding]=useState<CustomerReturnSummary|null>(null),[refundAmount,setRefundAmount]=useState(0),[refundReason,setRefundReason]=useState('')
  const load=async()=>{setLoading(true);const{data,error:e}=await supabase.rpc('get_customer_returns_overview');if(e)setError(userMessageFromError(e,'Impossible de charger les retours.'));else setItems((data||[])as CustomerReturnSummary[]);setLoading(false)}
  useEffect(()=>{void load()},[]);useEffect(()=>{if(canManage&&params.get('vente'))setOpen(true)},[params,canManage])
  const filtered=useMemo(()=>items.filter(i=>{const day=i.created_at.slice(0,10);return(!search||`${i.numero} ${i.vente_numero} ${i.client_nom||''}`.toLowerCase().includes(search.toLowerCase()))&&(!from||day>=from)&&(!to||day<=to)&&(stockFilter==='tous'||String(i.stock_reintegrable)===stockFilter)}),[items,search,from,to,stockFilter])
  const lookup=async()=>{setError('');const{data,error:e}=await supabase.rpc('get_sale_returnable_detail',{p_vente_id:saleId});if(e)setError(userMessageFromError(e,'Vente introuvable ou non accessible.'));else{setDetail(data as ReturnableSaleDetail);setQuantities({})}}
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!detail)return;setBusy(true);setError('');const lines=detail.lignes.map(l=>({ligne_vente_id:l.id,quantite:quantities[l.id]||0})).filter(l=>l.quantite>0);const result=cancelEntire?await supabase.rpc('cancel_sale',{p_vente_id:detail.vente.id,p_motif:reason,p_politique_stock:restoreStock?'reintegrer':'sans_reprise',p_politique_remboursement:refundMethod,p_idempotency_key:crypto.randomUUID()}):await supabase.rpc('create_customer_return',{p_vente_id:detail.vente.id,p_lignes:lines,p_stock_reintegrable:restoreStock,p_motif:reason,p_idempotency_key:crypto.randomUUID(),p_est_annulation:false});if(result.error)setError(userMessageFromError(result.error,'La correction n’a pas pu être créée.'));else{setOpen(false);setDetail(null);setSaleId('');setReason('');setRestoreStock(false);setCancelEntire(false);await load()}setBusy(false)}
  const submitRefund=async(e:FormEvent)=>{e.preventDefault();if(!refunding?.avoir_id)return;setBusy(true);setError('');const{error:e2}=await supabase.rpc('refund_customer',{p_avoir_id:refunding.avoir_id,p_montant:refundAmount,p_mode:refundMethod,p_motif:refundReason,p_idempotency_key:crypto.randomUUID(),p_reference:null});if(e2)setError(userMessageFromError(e2,'Le remboursement n’a pas pu être enregistré.'));else{setRefunding(null);setRefundReason('');await load()}setBusy(false)}
  return <><PageHeader title="Retours clients" description="Corrections de ventes, reprises de stock, remboursements et avoirs." action={canManage?<button className="btn-primary" onClick={()=>setOpen(true)}><Plus size={18}/>Créer une correction</button>:undefined}/>
    {error&&!open&&!refunding&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="card mb-5 grid gap-3 p-4 md:grid-cols-4"><div className="relative"><Search className="absolute left-3 top-3.5 text-slate-400" size={18}/><input className="field pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Retour, vente, client…"/></div><input className="field" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="field" type="date" value={to} onChange={e=>setTo(e.target.value)}/><select className="field" value={stockFilter} onChange={e=>setStockFilter(e.target.value)}><option value="tous">Tous les retours</option><option value="true">Stock réintégré</option><option value="false">Sans reprise stock</option></select></div>
    <div className="card overflow-x-auto">{loading?<div className="grid h-64 place-items-center"><LoaderCircle className="animate-spin"/></div>:<table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Retour / date</th><th>Vente</th><th>Client</th><th>Montant</th><th>Stock</th><th>Remboursé</th><th>Avoir ouvert</th><th>Auteur</th><th></th></tr></thead><tbody className="divide-y">{filtered.map(i=><tr key={i.id}><td className="p-4"><b className="text-brand-700">{i.numero}</b><p className="text-xs text-slate-500">{formatDateTime(i.created_at)}</p></td><td>{i.vente_numero}</td><td>{i.client_nom||'—'}</td><td className="font-bold">{formatMoney(i.montant)}</td><td>{i.stock_reintegrable?'Réintégré':'Non repris'}</td><td>{formatMoney(i.montant_rembourse)}</td><td>{formatMoney(i.avoir_disponible)}</td><td>{i.auteur}</td><td>{canManage&&i.avoir_id&&Number(i.avoir_disponible)>0&&<button className="btn-secondary" onClick={()=>{setRefunding(i);setRefundAmount(Number(i.avoir_disponible));setRefundMethod('especes')}}>Rembourser</button>}</td></tr>)}</tbody></table>}{!loading&&!filtered.length&&<p className="p-10 text-center text-slate-500">Aucun retour trouvé.</p>}</div>
    {open&&<div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={submit} className="card my-6 w-full max-w-2xl p-6"><div className="mb-5 flex justify-between"><div><p className="text-xs font-bold text-brand-600">CORRECTION</p><h2 className="text-xl font-black">Retour ou annulation</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><label className="label">Identifiant de la vente</label><div className="flex gap-2"><input required className="field" value={saleId} onChange={e=>setSaleId(e.target.value)} placeholder="UUID de la vente"/><button type="button" className="btn-secondary" onClick={()=>void lookup()}><Search size={18}/>Charger</button></div>{detail&&<><p className="my-4 rounded-xl bg-brand-50 p-3 font-bold">{detail.vente.numero} · {formatMoney(detail.vente.total_final)}</p><label className="mb-4 flex gap-2 font-bold"><input type="checkbox" checked={cancelEntire} onChange={e=>setCancelEntire(e.target.checked)}/>Annulation totale de la vente</label>{!cancelEntire&&<div className="space-y-2">{detail.lignes.map(line=>{const max=returnableQuantity(line.quantite_vendue,line.quantite_retournee);return <div key={line.id} className="grid grid-cols-[1fr_130px] items-center gap-3 rounded-xl border p-3"><div><b>{line.nom}</b><p className="text-xs text-slate-500">Vendu {line.quantite_vendue} · déjà retourné {line.quantite_retournee} · {formatMoney(line.prix_unitaire)}</p></div><input className="field" type="number" min="0" max={max} step="1" value={quantities[line.id]||''} onChange={e=>setQuantities({...quantities,[line.id]:Number(e.target.value)})} placeholder={`Max ${max}`}/></div>})}</div>}<label className="mt-4 flex items-start gap-3 rounded-xl bg-amber-50 p-3 text-sm"><input className="mt-1" type="checkbox" checked={restoreStock} onChange={e=>setRestoreStock(e.target.checked)}/><span><b>Réintégrer le stock</b><br/>Uniquement si les matières ou produits sont réellement récupérables.</span></label>{cancelEntire&&<><label className="label mt-4">Traitement du trop-perçu</label><select className="field" value={refundMethod} onChange={e=>setRefundMethod(e.target.value as RefundMethod)}><option value="avoir">Conserver en avoir</option><option value="especes">Rembourser en espèces</option><option value="orange_money">Orange Money</option><option value="moov_money">Moov Money</option><option value="virement">Virement</option></select></>}<label className="label mt-4">Motif obligatoire</label><textarea required className="field" value={reason} onChange={e=>setReason(e.target.value)}/></>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy||!detail||!reason.trim()} className="btn-primary mt-5 w-full">{busy?<LoaderCircle className="animate-spin" size={18}/>:<RotateCcw size={18}/>}Valider la correction</button></form></div>}
    {refunding&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={submitRefund} className="card w-full max-w-md p-6"><div className="flex justify-between"><div><p className="text-xs font-bold text-brand-600">{refunding.numero}</p><h2 className="text-xl font-black">Rembourser l’avoir</h2></div><button type="button" onClick={()=>setRefunding(null)}><X/></button></div><p className="my-4 rounded-xl bg-brand-50 p-3">Disponible : <b>{formatMoney(refunding.avoir_disponible)}</b></p><label className="label">Montant</label><input required className="field" type="number" min="1" max={refunding.avoir_disponible} value={refundAmount||''} onChange={e=>setRefundAmount(Number(e.target.value))}/><label className="label mt-3">Mode</label><select className="field" value={refundMethod} onChange={e=>setRefundMethod(e.target.value as RefundMethod)}><option value="especes">Espèces</option><option value="orange_money">Orange Money</option><option value="moov_money">Moov Money</option><option value="virement">Virement</option></select><label className="label mt-3">Motif</label><textarea required className="field" value={refundReason} onChange={e=>setRefundReason(e.target.value)}/>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="btn-primary mt-5 w-full">Confirmer le remboursement</button></form></div>}
  </>
}
