import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { CreditCard, Eye, LoaderCircle, Plus, Search, UserRound, X } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { useAuth } from '../contexts/AuthContext'
import { EMPTY_CUSTOMER_FORM, saveCustomerRecord } from '../lib/customers'
import { userMessageFromError } from '../lib/errors'
import { formatDateTime, formatMoney } from '../lib/format'
import { supabase } from '../lib/supabase'
import type { PaymentMethod } from '../types/database'
import type { Customer, CustomerDetail, CustomerSale } from '../types/customers'

const paymentLabels:Record<PaymentMethod,string>={especes:'Espèces',orange_money:'Orange Money',moov_money:'Moov Money',autre:'Autre'}

export function CustomersPage(){
  const{profile}=useAuth(),[customers,setCustomers]=useState<Customer[]>([]),[search,setSearch]=useState(''),[debtOnly,setDebtOnly]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState<Customer|null|undefined>(undefined),[form,setForm]=useState(EMPTY_CUSTOMER_FORM),[detail,setDetail]=useState<CustomerDetail|null>(null),[paying,setPaying]=useState<CustomerSale|null>(null),[payment,setPayment]=useState({montant:0,mode:'especes' as PaymentMethod,reference:'',note:''}),[busy,setBusy]=useState(false)
  const canManage=profile?.role==='admin'||profile?.role==='gestionnaire',canPay=canManage||profile?.role==='caissier'
  const load=async()=>{setLoading(true);const{data,error:e}=await supabase.rpc('get_customers_overview',{p_search:null,p_only_with_debt:false});if(e)setError(userMessageFromError(e,'Impossible de charger les clients.'));else setCustomers((data||[])as Customer[]);setLoading(false)}
  useEffect(()=>{void load()},[])
  const filtered=useMemo(()=>customers.filter(c=>(!debtOnly||Number(c.encours_credit)>0)&&[c.nom,c.numero,c.telephone||''].some(v=>v.toLowerCase().includes(search.toLowerCase()))),[customers,search,debtOnly])
  const openForm=(customer:Customer|null)=>{setEditing(customer);setForm(customer?{nom:customer.nom,telephone:customer.telephone||'',email:customer.email||'',adresse:customer.adresse||'',plafond_credit:Number(customer.plafond_credit),actif:customer.actif}:{...EMPTY_CUSTOMER_FORM});setError('')}
  const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await saveCustomerRecord(form,editing?.id||null);setEditing(undefined);await load()}catch(rpcError){setError(userMessageFromError(rpcError,'Le client n’a pas pu être enregistré.'))}finally{setBusy(false)}}
  const openDetail=async(id:string)=>{setError('');const{data,error:e}=await supabase.rpc('get_customer_detail',{p_client_id:id});if(e)setError(userMessageFromError(e,'Impossible de charger le client.'));else setDetail(data as CustomerDetail)}
  const pay=async(e:FormEvent)=>{e.preventDefault();if(!paying)return;setBusy(true);const{error:rpcError}=await supabase.rpc('add_customer_payment',{p_vente_id:paying.id,p_montant:payment.montant,p_mode_paiement:payment.mode,p_idempotency_key:crypto.randomUUID(),p_reference:payment.reference||null,p_note:payment.note||null});if(rpcError)setError(userMessageFromError(rpcError,'Le règlement n’a pas pu être enregistré.'));else{const id=detail?.id;setPaying(null);setPayment({montant:0,mode:'especes',reference:'',note:''});await load();if(id)await openDetail(id)}setBusy(false)}
  return <><PageHeader title="Clients" description="Créances, plafonds de crédit, règlements et fidélité." action={canManage?<div className="flex gap-2"><a className="btn-secondary" href="/retours">Retours clients</a><button className="btn-primary" onClick={()=>openForm(null)}><Plus size={18}/>Nouveau client</button></div>:undefined}/>
    {error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
    <div className="card mb-4 grid gap-3 p-4 sm:grid-cols-[1fr_auto]"><div className="relative"><Search className="absolute left-3 top-3.5 text-slate-400" size={18}/><input className="field pl-10" placeholder="Nom, numéro ou téléphone…" value={search} onChange={e=>setSearch(e.target.value)}/></div><label className="flex items-center gap-2 rounded-xl bg-slate-50 px-4 text-sm font-bold"><input type="checkbox" checked={debtOnly} onChange={e=>setDebtOnly(e.target.checked)}/>Créances uniquement</label></div>
    <div className="card overflow-x-auto">{loading?<div className="grid h-64 place-items-center"><LoaderCircle className="animate-spin"/></div>:<table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Client</th><th>Téléphone</th><th>Plafond</th><th>Créance</th><th>Disponible</th><th>Points</th><th>État</th><th></th></tr></thead><tbody className="divide-y">{filtered.map(c=><tr key={c.id}><td className="p-4"><b>{c.nom}</b><p className="text-xs text-brand-600">{c.numero}</p></td><td>{c.telephone||'—'}</td><td>{formatMoney(c.plafond_credit)}</td><td className="font-bold text-red-600">{formatMoney(c.encours_credit)}</td><td>{formatMoney(Math.max(0,Number(c.plafond_credit)-Number(c.encours_credit)))}</td><td>{c.points_fidelite}</td><td>{c.actif?'Actif':'Inactif'}</td><td className="space-x-2 text-right">{canManage&&<button className="btn-secondary min-h-9 px-3 py-1" onClick={()=>openForm(c)}>Modifier</button>}<button className="rounded-lg p-2 hover:bg-slate-100" onClick={()=>void openDetail(c.id)}><Eye size={18}/></button></td></tr>)}</tbody></table>}</div>
    {editing!==undefined&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form className="card w-full max-w-lg p-6" onSubmit={save}><div className="mb-5 flex justify-between"><h2 className="text-xl font-black">{editing?'Modifier le client':'Nouveau client'}</h2><button type="button" onClick={()=>setEditing(undefined)}><X/></button></div><div className="space-y-3"><div><label className="label">Nom</label><input required className="field" value={form.nom} onChange={e=>setForm({...form,nom:e.target.value})}/></div><div className="grid gap-3 sm:grid-cols-2"><div><label className="label">Téléphone</label><input className="field" value={form.telephone} onChange={e=>setForm({...form,telephone:e.target.value})}/></div><div><label className="label">Email</label><input type="email" className="field" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div></div><div><label className="label">Adresse</label><input className="field" value={form.adresse} onChange={e=>setForm({...form,adresse:e.target.value})}/></div><div><label className="label">Plafond de crédit</label><input className="field" type="number" min="0" value={form.plafond_credit} onChange={e=>setForm({...form,plafond_credit:Number(e.target.value)})}/></div><label className="flex gap-2"><input type="checkbox" checked={form.actif} onChange={e=>setForm({...form,actif:e.target.checked})}/>Client actif</label></div><button disabled={busy} className="btn-primary mt-5 w-full">Enregistrer</button></form></div>}
    {detail&&<div className="fixed inset-0 z-40 flex justify-end bg-slate-950/60"><button className="absolute inset-0" onClick={()=>setDetail(null)}/><div className="relative h-full w-full max-w-3xl overflow-y-auto bg-white p-6"><div className="flex justify-between"><div><p className="text-xs font-bold text-brand-600">{detail.numero}</p><h2 className="text-2xl font-black">{detail.nom}</h2></div><button onClick={()=>setDetail(null)}><X/></button></div><div className="my-5 grid grid-cols-3 gap-3"><div className="rounded-xl bg-red-50 p-3"><p className="text-xs">Créance</p><b>{formatMoney(detail.encours_credit)}</b></div><div className="rounded-xl bg-blue-50 p-3"><p className="text-xs">Plafond</p><b>{formatMoney(detail.plafond_credit)}</b></div><div className="rounded-xl bg-amber-50 p-3"><p className="text-xs">Fidélité</p><b>{detail.points_fidelite} points</b></div></div><h3 className="mb-2 font-black">Ventes</h3><div className="space-y-2">{detail.ventes.map(v=><div key={v.id} className="flex items-center justify-between rounded-xl border p-3"><div><b>{v.numero}</b><p className="text-xs text-slate-500">{formatDateTime(v.created_at)} · Total {formatMoney(v.total_final)}</p></div><div className="text-right"><b className={v.reste_a_payer>0?'text-red-600':'text-emerald-600'}>Reste {formatMoney(v.reste_a_payer)}</b>{canPay&&v.reste_a_payer>0&&<button className="ml-3 rounded-lg bg-brand-600 p-2 text-white" onClick={()=>{setPaying(v);setPayment({...payment,montant:Number(v.reste_a_payer)})}}><CreditCard size={17}/></button>}</div></div>)}</div><h3 className="mb-2 mt-6 font-black">Règlements</h3><div className="space-y-2">{detail.paiements.map(p=><div key={p.id} className="flex justify-between rounded-xl bg-slate-50 p-3"><span>{p.numero} · {paymentLabels[p.mode]}<small className="block text-slate-500">{formatDateTime(p.created_at)}</small></span><b>{formatMoney(p.montant)}</b></div>)}</div>{!detail.ventes.length&&<div className="py-12 text-center text-slate-400"><UserRound className="mx-auto"/>Aucune vente</div>}</div></div>}
    {paying&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form className="card w-full max-w-md p-6" onSubmit={pay}><div className="flex justify-between"><div><p className="text-xs text-brand-600">{paying.numero}</p><h2 className="text-xl font-black">Règlement client</h2></div><button type="button" onClick={()=>setPaying(null)}><X/></button></div><p className="my-4 rounded-xl bg-red-50 p-3">Reste dû : <b>{formatMoney(paying.reste_a_payer)}</b></p><label className="label">Montant</label><input required className="field" type="number" min="1" max={paying.reste_a_payer} value={payment.montant||''} onChange={e=>setPayment({...payment,montant:Number(e.target.value)})}/><label className="label mt-3">Mode</label><select className="field" value={payment.mode} onChange={e=>setPayment({...payment,mode:e.target.value as PaymentMethod})}>{Object.entries(paymentLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label className="label mt-3">Référence</label><input className="field" value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/><label className="label mt-3">Note</label><textarea className="field" value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})}/><button disabled={busy} className="btn-primary mt-5 w-full">Enregistrer le règlement</button></form></div>}
  </>
}
