import{useEffect,useState,type FormEvent}from'react'
import{PageHeader}from'../components/PageHeader'
import{supabase}from'../lib/supabase'
import{userMessageFromError}from'../lib/errors'
import{APP_NAME,APP_VERSION}from'../lib/version'
import{isValidRestaurantSettings}from'../lib/settings'
import{useAuth}from'../contexts/AuthContext'
import{UpdatePanel}from'../components/UpdatePanel'

interface Settings{nom:string;telephone:string|null;adresse:string|null;slogan:string|null;devise:string;logo_url:string|null;pied_ticket:string;numero_fiscal:string|null;largeur_ticket:number}
const empty:Settings={nom:'MG DELICES',telephone:null,adresse:null,slogan:null,devise:'F CFA',logo_url:null,pied_ticket:'Merci pour votre confiance.',numero_fiscal:null,largeur_ticket:80}
export function SettingsPage(){const{profile}=useAuth(),[settings,setSettings]=useState(empty),[error,setError]=useState(''),[saved,setSaved]=useState(false)
useEffect(()=>{supabase.rpc('get_restaurant_settings').then(({data,error:e})=>{if(e)setError(userMessageFromError(e));else setSettings(data as Settings)})},[])
const save=async(e:FormEvent)=>{e.preventDefault();setError('');setSaved(false);if(!isValidRestaurantSettings(settings)){setError('Le nom, la devise, le pied de ticket et la largeur doivent être valides.');return}const{data,error:failure}=await supabase.rpc('update_restaurant_settings',{p_settings:settings});if(failure)setError(userMessageFromError(failure));else{setSettings(data as Settings);setSaved(true)}}
return <><PageHeader title="Paramètres" description="Identité du restaurant, impression, sauvegardes et version."/><div className="grid gap-5 xl:grid-cols-2"><form className="card space-y-4 p-5" onSubmit={save}><h2 className="font-black">Restaurant et tickets</h2><input className="field" value={settings.nom} onChange={e=>setSettings({...settings,nom:e.target.value})} placeholder="Nom"/><input className="field" value={settings.telephone||''} onChange={e=>setSettings({...settings,telephone:e.target.value})} placeholder="Téléphone"/><input className="field" value={settings.adresse||''} onChange={e=>setSettings({...settings,adresse:e.target.value})} placeholder="Adresse"/><input className="field" value={settings.slogan||''} onChange={e=>setSettings({...settings,slogan:e.target.value})} placeholder="Slogan"/><input className="field" value={settings.logo_url||''} onChange={e=>setSettings({...settings,logo_url:e.target.value})} placeholder="URL du logo (facultatif)"/><textarea className="field" value={settings.pied_ticket} onChange={e=>setSettings({...settings,pied_ticket:e.target.value})} placeholder="Pied de ticket"/><select className="field" value={settings.largeur_ticket} onChange={e=>setSettings({...settings,largeur_ticket:Number(e.target.value)})}><option value={80}>Ticket 80 mm</option><option value={58}>Ticket 58 mm</option></select>{error&&<p className="text-sm text-red-700">{error}</p>}{saved&&<p className="text-sm text-emerald-700">Paramètres enregistrés.</p>}<button disabled={profile?.role!=='admin'} className="btn-primary">Enregistrer</button>{profile?.role!=='admin'&&<p className="text-xs text-slate-500">Modification réservée aux administrateurs.</p>}</form><div className="space-y-5"><section className="card p-5"><h2 className="font-black">À propos</h2><p className="mt-3 text-2xl font-black">{APP_NAME}</p><p>Version actuelle : {APP_VERSION}</p><UpdatePanel/></section><section className="card p-5"><h2 className="font-black">Sauvegardes</h2><p className="mt-2 text-sm text-slate-600">Les exports fonctionnels sont disponibles dans Rapports. Une sauvegarde complète doit être réalisée via les sauvegardes Supabase ou <code>pg_dump</code> depuis un environnement administrateur sécurisé, jamais depuis le navigateur.</p></section></div></div></>}
