import { useEffect, useState, type FormEvent } from 'react'
import { LoaderCircle, Plus, RotateCcw, Search, X } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { userMessageFromError } from '../lib/errors'
import { formatDateTime, formatMoney } from '../lib/format'
import { returnableQuantity } from '../lib/returns'
import { supabase } from '../lib/supabase'
import type { ReturnablePurchaseDetail, SupplierReturnSummary } from '../types/returns'

export function SupplierReturnsPage(){
  const[params]=useSearchParams(),[items,setItems]=useState<SupplierReturnSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[purchaseId,setPurchaseId]=useState(params.get('achat')||''),[detail,setDetail]=useState<ReturnablePurchaseDetail|null>(null),[quantities,setQuantities]=useState<Record<string,number>>({}),[reason,setReason]=useState(''),[busy,setBusy]=useState(false)
  const load=async()=>{setLoading(true);const{data,error:e}=await supabase.rpc('get_supplier_returns_overview');if(e)setError(userMessageFromError(e,'Impossible de charger les retours fournisseurs.'));else setItems((data||[])as SupplierReturnSummary[]);setLoading(false)}
  useEffect(()=>{void load()},[]);useEffect(()=>{if(params.get('achat'))setOpen(true)},[params])
  const lookup=async()=>{const{data,error:e}=await supabase.rpc('get_purchase_returnable_detail',{p_achat_id:purchaseId});if(e)setError(userMessageFromError(e,'Achat réceptionné introuvable.'));else{setDetail(data as ReturnablePurchaseDetail);setQuantities({})}}
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!detail)return;const lignes=detail.lignes.map(l=>({ligne_achat_id:l.id,quantite:quantities[l.id]||0})).filter(l=>l.quantite>0);setBusy(true);const{error:e2}=await supabase.rpc('create_supplier_return',{p_achat_id:detail.achat.id,p_lignes:lignes,p_motif:reason,p_idempotency_key:crypto.randomUUID()});if(e2)setError(userMessageFromError(e2,'Le retour fournisseur n’a pas pu être créé.'));else{setOpen(false);setDetail(null);setReason('');await load()}setBusy(false)}
  return <><PageHeader title="Retours fournisseurs" description="Retours de matières réceptionnées et avoirs fournisseurs." action={<button className="btn-primary" onClick={()=>setOpen(true)}><Plus size={18}/>Créer un retour</button>}/>{error&&!open&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="card overflow-x-auto">{loading?<div className="grid h-64 place-items-center"><LoaderCircle className="animate-spin"/></div>:<table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Retour</th><th>Achat</th><th>Fournisseur</th><th>Montant</th><th>Avoir ouvert</th><th>Date</th><th>Auteur</th></tr></thead><tbody className="divide-y">{items.map(i=><tr key={i.id}><td className="p-4 font-bold text-brand-700">{i.numero}</td><td>{i.numero_achat}</td><td>{i.fournisseur_nom}</td><td>{formatMoney(i.montant)}</td><td>{formatMoney(i.avoir_disponible)}</td><td>{formatDateTime(i.created_at)}</td><td>{i.auteur}</td></tr>)}</tbody></table>}{!loading&&!items.length&&<p className="p-10 text-center text-slate-500">Aucun retour fournisseur.</p>}</div>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/60 p-4"><form onSubmit={submit} className="card my-6 w-full max-w-2xl p-6"><div className="mb-5 flex justify-between"><div><p className="text-xs font-bold text-brand-600">APPROVISIONNEMENT</p><h2 className="text-xl font-black">Retour fournisseur</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div><label className="label">Identifiant de l’achat réceptionné</label><div className="flex gap-2"><input required className="field" value={purchaseId} onChange={e=>setPurchaseId(e.target.value)} placeholder="UUID de l’achat"/><button type="button" className="btn-secondary" onClick={()=>void lookup()}><Search size={18}/>Charger</button></div>{detail&&<><p className="my-4 rounded-xl bg-brand-50 p-3 font-bold">{detail.achat.numero_achat} · {detail.fournisseur_nom}</p><div className="space-y-2">{detail.lignes.map(line=>{const max=returnableQuantity(Number(line.quantite_recue),Number(line.quantite_retournee));return <div key={line.id} className="grid grid-cols-[1fr_150px] items-center gap-3 rounded-xl border p-3"><div><b>{line.nom}</b><p className="text-xs text-slate-500">Reçu {line.quantite_recue} {line.unite} · retourné {line.quantite_retournee} · {formatMoney(line.cout_unitaire)}</p></div><input className="field" type="number" min="0" max={max} step="0.001" value={quantities[line.id]||''} onChange={e=>setQuantities({...quantities,[line.id]:Number(e.target.value)})} placeholder={`Max ${max}`}/></div>})}</div><label className="label mt-4">Motif obligatoire</label><textarea required className="field" value={reason} onChange={e=>setReason(e.target.value)}/></>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy||!detail||!reason.trim()} className="btn-primary mt-5 w-full">{busy?<LoaderCircle className="animate-spin" size={18}/>:<RotateCcw size={18}/>}Valider le retour fournisseur</button></form></div>}</>
}
