import{useEffect,useState}from'react'
import{PageHeader}from'../../components/PageHeader'
import{supabase}from'../../lib/supabase'
import{userMessageFromError}from'../../lib/errors'

interface AuditRow{id:number;created_at:string;actor_name:string|null;action:string;domaine:string;objet_type:string;objet_id:string|null;reference_metier:string|null;donnees_avant:unknown;donnees_apres:unknown}
export function AuditPage(){const[rows,setRows]=useState<AuditRow[]>([]),[offset,setOffset]=useState(0),[filters,setFilters]=useState({from:'',to:'',domain:'',action:'',reference:''}),[error,setError]=useState('')
const load=async()=>{const{data,error:e}=await supabase.rpc('get_audit_log',{p_from:filters.from||null,p_to:filters.to||null,p_actor:null,p_domain:filters.domain||null,p_action:filters.action||null,p_object_type:null,p_reference:filters.reference||null,p_limit:100,p_offset:offset});if(e)setError(userMessageFromError(e));else setRows(((data as{rows:AuditRow[]}).rows||[]))}
useEffect(()=>{void load()},[offset,filters.from,filters.to,filters.domain,filters.action,filters.reference])
return <><PageHeader title="Journal d’audit" description="Consultation immuable des opérations sensibles."/><div className="card mb-5 grid gap-3 p-4 md:grid-cols-5"><input className="field" type="date" value={filters.from} onChange={e=>{setOffset(0);setFilters({...filters,from:e.target.value})}}/><input className="field" type="date" value={filters.to} onChange={e=>{setOffset(0);setFilters({...filters,to:e.target.value})}}/><input className="field" placeholder="Domaine" value={filters.domain} onChange={e=>{setOffset(0);setFilters({...filters,domain:e.target.value})}}/><input className="field" placeholder="Action" value={filters.action} onChange={e=>{setOffset(0);setFilters({...filters,action:e.target.value})}}/><input className="field" placeholder="Référence" value={filters.reference} onChange={e=>{setOffset(0);setFilters({...filters,reference:e.target.value})}}/></div>{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="card overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Date</th><th>Utilisateur</th><th>Domaine</th><th>Action</th><th>Objet</th><th>Référence</th><th>Détails</th></tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.id}><td className="p-3">{new Date(row.created_at).toLocaleString('fr-FR')}</td><td>{row.actor_name||'Système'}</td><td>{row.domaine}</td><td>{row.action}</td><td>{row.objet_type}</td><td>{row.reference_metier||row.objet_id||'—'}</td><td><details><summary className="cursor-pointer">Voir</summary><pre className="max-w-md overflow-auto text-xs">{JSON.stringify({avant:row.donnees_avant,apres:row.donnees_apres},null,2)}</pre></details></td></tr>)}</tbody></table></div><div className="mt-4 flex justify-end gap-3"><button className="btn-secondary" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-100))}>Précédent</button><button className="btn-secondary" disabled={rows.length<100} onClick={()=>setOffset(offset+100)}>Suivant</button></div></>}
